version: '3'

services:
  mongo_pop:
    image: bitnami/mongodb:4.2
    hostname: "mongo"
    expose: 
      - "27017"
    ports: 
      - "27017:27017"
    volumes:
      - .:/data
    environment:
      - MONGODB_DATA_DIR=/data/mongo
